#!/usr/bin/env python3
"""Build the chatbot's system prompt from the niro-negotiation skill.

Output:
  prompt/system-prompt.md   read by serve.py (tailnet)
  functions/_prompt.js      imported by the Cloudflare Pages Function

Run after any edit to skills/niro-negotiation or prompt/preamble.md. The prompt
must stay byte-identical between requests or prompt caching stops hitting, so
never add timestamps or anything else that varies.
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.normpath(os.path.join(HERE, "..", "..", "skills", "niro-negotiation"))

# SKILL.md sections that make sense for any user. The rest is Porter-specific
# (his deals, his other skills, the Cowork update procedure).
KEEP_SECTIONS = ["The Method in Five Moves", "Modes of Engagement", "What This Skill Is Missing"]
REFERENCES = ["prep-worksheet.md", "principles-and-evidence.md", "sources.md"]

# Porter-specific phrasings -> public phrasings. Order matters: longest first.
REWRITES = [
    ("Porter can watch it and add notes.", "It is not available to this coach."),
    ("When Porter is the bigger party (a group CRO buying, a client with an alternative), be most suspicious of his certainty.",
     "When the user is the bigger party (a large buyer, a client with alternatives), be most suspicious of their certainty."),
    ("where he needs commitment", "where they need commitment"),
    (" Members only (Porter has access).", " Members only."),
    ("every claim in SKILL.md", "every claim in the method above"),
    ("Tags follow SKILL.md.", "Tags as in the method above."),
    ("(from the `ypo-lbs-2026` notes)", ""),
    ("The full version is in `ypo-lbs-2026/references/professors/niro-sivanathan-influence.md`.", ""),
    ("Niro's LBS 2026 notes", "Niro's LBS 2026 programme"),
    ("Porter's LBS 2026 notes", "notes from Niro's LBS 2026 programme"),
    ("Porter's deals", "typical deals"),
    ("Porter's", "the user's"),
    ("Porter", "the user"),
]


def sections(md):
    """Split markdown into {h2 title: text including heading}."""
    out, cur, buf = {}, None, []
    for line in md.splitlines(keepends=True):
        m = re.match(r"^## (.+?)\s*$", line)
        if m:
            if cur:
                out[cur] = "".join(buf)
            cur, buf = m.group(1), [line]
        elif cur:
            buf.append(line)
    if cur:
        out[cur] = "".join(buf)
    return out


def rewrite(text):
    for a, b in REWRITES:
        text = text.replace(a, b)
    # Pointers into Porter's private skill fleet mean nothing to other users.
    text = "\n".join(l for l in text.splitlines()
                     if "ypo-lbs-2026" not in l and "codingscape-ceo" not in l
                     and "Already captured:" not in l)
    return text.rstrip() + "\n"


def build():
    parts = [open(os.path.join(HERE, "prompt", "preamble.md")).read().rstrip() + "\n"]
    secs = sections(open(os.path.join(SKILL, "SKILL.md")).read())
    missing = [s for s in KEEP_SECTIONS if s not in secs]
    if missing:
        raise SystemExit("SKILL.md is missing sections: %s" % missing)
    for s in KEEP_SECTIONS:
        parts.append(rewrite(secs[s]))
    for ref in REFERENCES:
        body = open(os.path.join(SKILL, "references", ref)).read()
        parts.append("\n---\n\n<!-- reference: %s -->\n\n%s" % (ref, rewrite(body)))
    prompt = "\n".join(parts)
    leftover = re.findall(r".{0,40}Porter.{0,40}", prompt)
    if leftover:
        raise SystemExit("Porter-specific text left in prompt: %s" % leftover)

    os.makedirs(os.path.join(HERE, "prompt"), exist_ok=True)
    with open(os.path.join(HERE, "prompt", "system-prompt.md"), "w") as f:
        f.write(prompt)
    os.makedirs(os.path.join(HERE, "functions"), exist_ok=True)
    with open(os.path.join(HERE, "functions", "_prompt.js"), "w") as f:
        f.write("// Generated by build_prompt.py. Do not edit.\n")
        f.write("export const SYSTEM_PROMPT = %s;\n" % json.dumps(prompt))
    print("system prompt: %d chars" % len(prompt))


if __name__ == "__main__":
    build()
