#!/bin/bash
# Niro Method coach: one-time installer for the Mac mini (tailnet only).
# Generated by make_installer.py. Run once in Terminal:  bash install-niro-coach.sh
# Re-running is safe: it updates the code and keeps config.json (your API key).
set -euo pipefail

APP="$HOME/niro-coach-live"
PORT=8793
MOUNT=/niro
LABEL=com.porter.niro-coach-server
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
TS=/Applications/Tailscale.app/Contents/MacOS/Tailscale

say() { printf '\n\033[1m%s\033[0m\n' "$*"; }
die() { printf '\n\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# 1. Port must be free, or already ours (re-install).
if lsof -nP -iTCP:$PORT -sTCP:LISTEN >/dev/null 2>&1; then
  if ! launchctl list 2>/dev/null | grep -- "$LABEL" >/dev/null; then
    die "Port $PORT is in use by something else. Edit PORT in this script and in config.json."
  fi
fi

# 2. Python >= 3.10 (the Anthropic SDK needs it; macOS's /usr/bin/python3 is 3.9).
PY=""
for c in /opt/homebrew/bin/python3 /usr/local/bin/python3 python3.13 python3.12 python3.11 python3.10 python3; do
  p=$(command -v "$c" 2>/dev/null || true)
  [ -n "$p" ] || continue
  if "$p" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)' 2>/dev/null; then PY="$p"; break; fi
done
[ -n "$PY" ] || die "Need Python 3.10+. Run: brew install python@3.12  then re-run this script."
say "Using $PY ($("$PY" --version))"

# 3. Unpack the app (serve.py, public/, prompt/). config.json is never overwritten.
say "Installing to $APP"
mkdir -p "$APP"
sed -n '/^__PAYLOAD__$/,$p' "$0" | tail -n +2 | base64 -D | tar -xz -C "$APP"

# 4. Private virtualenv with the Anthropic SDK.
[ -x "$APP/.venv/bin/python" ] || "$PY" -m venv "$APP/.venv"
"$APP/.venv/bin/pip" install -q --upgrade pip
"$APP/.venv/bin/pip" install -q 'anthropic>=1.8,<2'

# 5. config.json sits ABOVE public/, so the web server can never serve the key.
if [ ! -f "$APP/config.json" ]; then
  KEY="${ANTHROPIC_API_KEY:-}"
  if [ -z "$KEY" ]; then
    printf 'Anthropic API key (input hidden): '
    read -rs KEY; echo
  fi
  [ -n "$KEY" ] || die "No API key given."
  KEY="$KEY" PORT="$PORT" "$APP/.venv/bin/python" - "$APP/config.json" <<'PYEOF'
import json, os, sys
json.dump({"anthropic_api_key": os.environ["KEY"], "port": int(os.environ["PORT"]),
           "model": "claude-opus-5", "effort": "medium", "max_tokens": 32000},
          open(sys.argv[1], "w"), indent=2)
PYEOF
  chmod 600 "$APP/config.json"
fi

# 6. Check the key works (lists one model; costs nothing).
say "Checking the API key"
"$APP/.venv/bin/python" - "$APP/config.json" <<'PYEOF' || die "API key check failed. Fix anthropic_api_key in $APP/config.json and re-run."
import json, sys, anthropic
cfg = json.load(open(sys.argv[1]))
anthropic.Anthropic(api_key=cfg["anthropic_api_key"]).models.retrieve(cfg.get("model", "claude-opus-5"))
print("  key OK")
PYEOF

# 7. launchd: keep the server running, start at login.
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key><array><string>$APP/.venv/bin/python</string><string>$APP/serve.py</string></array>
  <key>WorkingDirectory</key><string>$APP</string>
  <key>KeepAlive</key><true/><key>RunAtLoad</key><true/>
  <key>StandardErrorPath</key><string>$APP/server.log</string>
  <key>StandardOutPath</key><string>$APP/server.log</string>
</dict></plist>
EOF
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load "$PLIST"
sleep 2

# 8. Publish to the tailnet only (serve, never funnel).
say "Publishing at $MOUNT on the tailnet"
"$TS" serve --bg --https=443 --set-path "$MOUNT" "http://127.0.0.1:$PORT"

# 9. Verify.
say "Verifying"
code=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/")
[ "$code" = 200 ] && echo "  page: 200 OK" || die "Page returned $code. See $APP/server.log"
code=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/config.json")
[ "$code" = 404 ] && echo "  config.json not served: OK" || die "config.json is reachable ($code). Stop and investigate."
"$TS" serve status 2>&1 | grep -- "$MOUNT" >/dev/null && echo "  tailscale serve: $MOUNT mapped" || die "tailscale serve did not register $MOUNT"
if "$TS" funnel status 2>/dev/null | grep "Funnel on" >/dev/null; then
  echo "  WARNING: some path is funneled to the public internet. Check: $TS funnel status"
else
  echo "  funnel: off (tailnet only)"
fi

# 10. Hub tile. The hub (~/hub-live) finds /niro by itself from `tailscale serve status`;
#     this just gives the tile a proper name. Guarded: any surprise leaves refresh.py alone.
HUB="$HOME/hub-live/refresh.py"
if [ -f "$HUB" ]; then
  if "$APP/.venv/bin/python" - "$HUB" "$MOUNT" <<'PYEOF'
import py_compile, re, shutil, sys
path, mount = sys.argv[1], sys.argv[2]
src = open(path).read()
if re.search(r"""["']%s["']\s*:""" % re.escape(mount), src):
    print("  hub: tile already named"); sys.exit(0)
m = re.search(r"^NAME\s*=\s*\{", src, re.M)
# Only edit if NAME is keyed by mount paths like "/weather".
if not m or not re.search(r"""["']/[a-z][\w/-]*["']\s*:""", src[m.end():m.end() + 2000]):
    print("  hub: NAME dict not recognised; tile will show with its default label"); sys.exit(1)
backup = path + ".pre-niro"
shutil.copy2(path, backup)
open(path, "w").write(src[:m.end()] + '\n    "%s": "Niro Method",' % mount + src[m.end():])
try:
    py_compile.compile(path, doraise=True)
except py_compile.PyCompileError:
    shutil.copy2(backup, path); print("  hub: edit failed to compile; restored refresh.py"); sys.exit(1)
print("  hub: tile named 'Niro Method' (backup at %s)" % backup)
PYEOF
  then
    launchctl kickstart -k "gui/$(id -u)/com.porter.hub-refresh" 2>/dev/null || true
  fi
else
  echo "  hub: ~/hub-live not found; skipping"
fi

HOST=$("$TS" status --json 2>/dev/null | "$APP/.venv/bin/python" -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))' 2>/dev/null || echo "mac-mini.tailc59509.ts.net")
say "Done. Open https://$HOST$MOUNT on any of your devices."
echo "  Logs:    $APP/server.log (metadata only, never chat content)"
echo "  Config:  $APP/config.json (model, effort, max_tokens; restart after edits:"
echo "           launchctl kickstart -k gui/\$(id -u)/$LABEL )"
echo "  Hub:     https://$HOST/ lists it under Private"
exit 0
__PAYLOAD__
